version: "3.9"
services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_DB: "ABD_lab1"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"